#pragma once
#ifndef PROGRESSION_TABLE_DEFINES_HPP
#define PROGRESSION_TABLE_DEFINES_HPP

#define ROOT_MENU_MARGIN 20
#define TOP_MENU_HEIGHT 25
#define SEARCH_MENU_HEIGHT 40

#define POPUP_TITLE "Blitzkrieg Progression"
#define TITLE_SCALE 0.45f

#define BACKGROUND_COLOR_RGB 70,82,113
#define POPUP_SIZE_W 375.0f
#define POPUP_SIZE_H 225.0f

#define MANIPULATION_BUTTONS_HEIGHT 20

#endif // PROGRESSION_TABLE_DEFINES_HPP