#pragma once
#ifndef PROGRESS_NODE_DEFINES_HPP
#define PROGRESS_NODE_DEFINES_HPP

#define PROGRESS_MARGIN 2
#define PROGRESS_HEIGHT 18

#define PROGRESS_DESCRIPTOR_COLOR_CCC4 ccc4(0,0,0,90)

#endif // PROGRESS_NODE_DEFINES_HPP