#pragma once
#ifndef PROGRESSION_STAGE_NODE_DEFINES_HPP
#define PROGRESSION_STAGE_NODE_DEFINES_HPP

#define STAGE_BACKGROUND_CCC4 ccc4(0, 0, 0, 90)
#define STAGE_MENU_MARGIN 5
#define STAGE_MENU_HEIGHT 15
#define ROOT_MENU_MARGIN 5

#endif // PROGRESSION_STAGE_NODE_DEFINES_HPP