#pragma once
#ifndef SQUARE_SPRITES_DEFINES_HPP
#define SQUARE_SPRITES_DEFINES_HPP

#define WHITE_SQUARE_SPRITE "GJ_square06.png"
#define PURPLE_SQUARE_SPRITE "GJ_square02.png"

#endif // SQUARE_SPRITES_DEFINES_HPP